spring:
  # 데이터 베이스 관련 설정
  datasource:
    #url: jdbc:mysql://localhost:3306/artfriendly?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    url: jdbc:mysql://database-1.cn0mmqiaop3v.ap-northeast-2.rds.amazonaws.com/artfriendly?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  # multipart 파일 용량 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  # 시큐리티 관련 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "https://artfriendly.duckdns.org/login/oauth2/code/kakao"
            #redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 사용자 인가 코드 받아오기 ?prompt=login-> 기존 로그인에 상관없이 로그인
            token-uri: https://kauth.kakao.com/oauth/token # 토큰 받아오기
            user-info-uri: https://kapi.kakao.com/v2/user/me # 사용자 정보 가져오기
            user-name-attribute: id # 카카오톡의 경우 "id"를 사용한다
# S3 관련 설정
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_BUCKET_ACCESSKEY}
      secret-key: ${S3_BUCKET_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

# 파일 경로 이름 설정
file:
  path:
    images: user_Image/

# JWT 관련 설정
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 360
  refresh-token-expiration-minutes: 43200

# api 연동 관련 설정
exhibition:
  code:
    art: D000
  api:
    duration: http://www.culture.go.kr/openapi/rest/publicperformancedisplays/period
    details: http://www.culture.go.kr/openapi/rest/publicperformancedisplays/d/
    realm: http://www.culture.go.kr/openapi/rest/publicperformancedisplays/realm
    credentials:
      service-key: ${API_SERVICEKEY}

profile:
  default-image: https://github.com/art-friendly-project/back-end/assets/68217405/f7d7d440-fde4-4d0d-b4fe-e3a4fa75d9bb

admin:
  email: ${ADMIN_EMAIL}

# 스레드 풀 설정
server:
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  port: 8080